name: Webページ更新

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B Workflow
        env:
          PAT: ${{ secrets.PAT }}  # リポジトリAのシークレットに設定したPAT
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $PAT" \
          https://api.github.com/repos/unyacat/inori-button/actions/workflows/update.yml/dispatches \
          -d '{"ref":"main"}'
